// SPDX-FileCopyrightText: 2026 ChipDesign B.V.
// SPDX-License-Identifier: Apache-2.0
//
// GENERATED by scripts/gen_fsm_bench.py -- do not edit by hand.
//
// Illegal state recovery for cdriscv_32s_20_core, on its gate netlist.
// See coverage waiver W2a and finding V24.

`default_nettype none
`timescale 1ns/1ps

module tb_fsm_cdriscv_core;

  logic clk = 0, rst_n;
  always #5ns clk = ~clk;

  localparam int RV32M = 1'b1;
  localparam int RfParity = 1'b1;
  localparam int HartId = 32'h0000_0000;
  localparam int MVendorId = 32'h0000_0000;
  localparam int MArchId = 32'h0000_0000;
  localparam int MImpId = 32'h0000_0001;

  logic [31:0] tb_boot_addr_i;
  logic  tb_fetch_enable_i;
  logic  tb_instr_gnt_i;
  logic  tb_instr_rvalid_i;
  logic [31:0] tb_instr_rdata_i;
  logic  tb_instr_err_i;
  logic  tb_data_gnt_i;
  logic  tb_data_rvalid_i;
  logic [31:0] tb_data_rdata_i;
  logic  tb_data_err_i;
  logic  tb_irq_soft_i;
  logic  tb_irq_timer_i;
  logic  tb_irq_ext_i;

  cdriscv_32s_20_core u_dut (
      .clk_i (clk),
      .rst_ni (rst_n),
      .boot_addr_i (tb_boot_addr_i),
      .fetch_enable_i (tb_fetch_enable_i),
      .instr_req_o (),
      .instr_gnt_i (tb_instr_gnt_i),
      .instr_rvalid_i (tb_instr_rvalid_i),
      .instr_addr_o (),
      .instr_rdata_i (tb_instr_rdata_i),
      .instr_err_i (tb_instr_err_i),
      .data_req_o (),
      .data_gnt_i (tb_data_gnt_i),
      .data_rvalid_i (tb_data_rvalid_i),
      .data_we_o (),
      .data_be_o (),
      .data_addr_o (),
      .data_wdata_o (),
      .data_rdata_i (tb_data_rdata_i),
      .data_err_i (tb_data_err_i),
      .irq_soft_i (tb_irq_soft_i),
      .irq_timer_i (tb_irq_timer_i),
      .irq_ext_i (tb_irq_ext_i),
      .fault_rf_par_o (),
      .fault_illegal_o (),
      .fault_bus_err_o (),
      .fault_sw_o (),
      .fault_out_en_o (),
      .core_sleep_o (),
      .retire_valid_o (),
      .retire_pc_o (),
      .retire_instr_o ()
  );

  int errors = 0, checks = 0;
  logic [2:0] idle, got, mask;
  bit         saw_req;
  int e, b;

  task automatic do_reset;
    rst_n = 0;
    tb_boot_addr_i = '0;
    tb_fetch_enable_i = '1;
    tb_instr_gnt_i = '1;
    tb_instr_rvalid_i = '1;
    tb_instr_rdata_i = '0;
    tb_instr_err_i = '0;
    tb_data_gnt_i = '1;
    tb_data_rvalid_i = '1;
    tb_data_rdata_i = '0;
    tb_data_err_i = '0;
    tb_irq_soft_i = '0;
    tb_irq_timer_i = '0;
    tb_irq_ext_i = '0;
    repeat (4) @(posedge clk);
    rst_n = 1;
    repeat (4) @(posedge clk);
  endtask

  initial begin
    do_reset();
    idle = u_dut.state_q;
    // Compare only the bits a flip-flop actually drives.  yosys
    // declares the state wire at its RTL width and optimises constant
    // bits away, so a four-bit declaration can have three flops and one
    // permanently floating bit -- and comparing that bit makes every
    // encoding look like a failure.
    mask = '0;
    for (b = 0; b < 3; b++)
      if (idle[b] === 1'b0 || idle[b] === 1'b1) mask[b] = 1'b1;
    $display("[fsm-cdriscv_32s_20_core] idle=%b driven=%b", idle, mask);

    for (e = 0; e < 8; e++) begin
      do_reset();
      force u_dut.state_q = 3'(e);
      @(posedge clk);
      #1ns;
      release u_dut.state_q;
      repeat (8) @(posedge clk);
      checks++;
      got = u_dut.state_q;
      // Every value of the driven bits is a legal state here --
      // ST_RUN, ST_WAIT_LSU, ST_WAIT_MD and ST_SLEEP use all four --
      // so "settled somewhere legal" is satisfied by construction and
      // says nothing.  The two checks that do say something are that
      // the state is defined, and that the core is still fetching
      // afterwards rather than wedged.
      if (((got ^ got) & mask) !== '0) begin
        $display("[fsm-cdriscv_32s_20_core] FAIL: encoding %0d left the state X (%b)", e, got);
        errors++;
      end else begin
        saw_req = 1'b0;
        fork
          begin repeat (200) begin @(posedge clk); if (u_dut.instr_req_o) saw_req = 1'b1; end end
        join
        checks++;
        if (!saw_req) begin
          $display("[fsm-cdriscv_32s_20_core] FAIL: encoding %0d left the core not fetching (state %b)",
                   e, got);
          errors++;
        end
      end
    end

    if (errors == 0)
      $display("[fsm-cdriscv_32s_20_core] PASS: 8 encodings, state defined and core still fetching");
    else
      $display("[fsm-cdriscv_32s_20_core] FAIL: %0d of %0d", errors, checks);
    $finish;
  end

  initial begin #5ms; $display("[fsm-cdriscv_32s_20_core] FAIL: timeout"); $finish; end

endmodule
