// SPDX-FileCopyrightText: 2026 ChipDesign B.V.
// SPDX-License-Identifier: Apache-2.0
//
// GENERATED by scripts/gen_fsm_bench.py -- do not edit by hand.
//
// Illegal state recovery for cdriscv_32s_20_mbist, on its gate netlist.
// See coverage waiver W2a and finding V24.

`default_nettype none
`timescale 1ns/1ps

module tb_fsm_cdriscv_mbist;

  logic clk = 0, rst_n;
  always #5ns clk = ~clk;

  logic  tb_psel_i;
  logic  tb_penable_i;
  logic [11:0] tb_paddr_i;
  logic  tb_pwrite_i;
  logic [31:0] tb_pwdata_i;
  logic [38:0] tb_bist_rdata_i;

  cdriscv_32s_20_mbist u_dut (
      .clk_i (clk),
      .rst_ni (rst_n),
      .psel_i (tb_psel_i),
      .penable_i (tb_penable_i),
      .paddr_i (tb_paddr_i),
      .pwrite_i (tb_pwrite_i),
      .pwdata_i (tb_pwdata_i),
      .prdata_o (),
      .psel_hit_o (),
      .pready_o (),
      .pslverr_o (),
      .busy_o (),
      .done_o (),
      .fail_o (),
      .bist_en_o (),
      .bist_we_o (),
      .bist_addr_o (),
      .bist_wdata_o (),
      .bist_rdata_i (tb_bist_rdata_i)
  );

  int errors = 0, checks = 0;
  logic [3:0] idle, got, mask;
  int e, b;

  task automatic do_reset;
    rst_n = 0;
    tb_psel_i = '0;
    tb_penable_i = '0;
    tb_paddr_i = '0;
    tb_pwrite_i = '0;
    tb_pwdata_i = '0;
    tb_bist_rdata_i = '0;
    repeat (4) @(posedge clk);
    rst_n = 1;
    repeat (4) @(posedge clk);
  endtask

  logic [3:0] done_state;

  // Run one normal BIST to completion and record where the machine
  // comes to rest.  A forced state restarts the march, so the machine
  // legitimately ends in BS_DONE rather than back in BS_IDLE -- both
  // are quiescent, defined states and both are a successful recovery.
  // Measuring it beats assuming it.
  task automatic run_normal_bist;
    @(posedge clk);
    tb_psel_i <= 1'b1; tb_penable_i <= 1'b0; tb_pwrite_i <= 1'b1;
    tb_paddr_i <= 12'h000; tb_pwdata_i <= 32'h1;
    @(posedge clk);
    tb_penable_i <= 1'b1;
    @(posedge clk);
    tb_psel_i <= 1'b0; tb_penable_i <= 1'b0; tb_pwrite_i <= 1'b0;
    repeat (2000) @(posedge clk);
  endtask

  initial begin
    do_reset();
    idle = u_dut.state_q;
    run_normal_bist();
    done_state = u_dut.state_q;
    $display("[fsm-cdriscv_32s_20_mbist] idle=%b terminal-after-run=%b", idle, done_state);
    do_reset();
    // Compare only the bits a flip-flop actually drives.  yosys
    // declares the state wire at its RTL width and optimises constant
    // bits away, so a four-bit declaration can have three flops and one
    // permanently floating bit -- and comparing that bit makes every
    // encoding look like a failure.
    mask = '0;
    for (b = 0; b < 4; b++)
      if (idle[b] === 1'b0 || idle[b] === 1'b1) mask[b] = 1'b1;
    $display("[fsm-cdriscv_32s_20_mbist] idle=%b driven=%b", idle, mask);

    for (e = 0; e < 16; e++) begin
      do_reset();
      force u_dut.state_q = 4'(e);
      @(posedge clk);
      #1ns;
      release u_dut.state_q;
      repeat (2000) @(posedge clk);   // a forced state restarts the march
      checks++;
      got = u_dut.state_q;
      if ((((got ^ idle) & mask) !== '0) && (((got ^ done_state) & mask) !== '0)) begin
        $display("[fsm-cdriscv_32s_20_mbist] FAIL: encoding %0d settled at %b, neither idle %b nor done %b",
                 e, got, idle, done_state);
        errors++;
      end
    end

    if (errors == 0)
      $display("[fsm-cdriscv_32s_20_mbist] PASS: 16 encodings all recover to a quiescent state");
    else
      $display("[fsm-cdriscv_32s_20_mbist] FAIL: %0d of %0d", errors, checks);
    $finish;
  end

  initial begin #5ms; $display("[fsm-cdriscv_32s_20_mbist] FAIL: timeout"); $finish; end

endmodule
