// SPDX-FileCopyrightText: 2026 ChipDesign B.V.
// SPDX-License-Identifier: Apache-2.0
//
// GENERATED by scripts/gen_fsm_bench.py -- do not edit by hand.
//
// Illegal state recovery for cdriscv_32s_20_ams_if, on its gate netlist.
// See coverage waiver W2a and finding V24.

`default_nettype none
`timescale 1ns/1ps

module tb_fsm_cdriscv_ams_if;

  logic clk = 0, rst_n;
  always #5ns clk = ~clk;

  localparam int NumCh = 8;
  localparam int AdcW = 12;

  logic  tb_psel_i;
  logic  tb_penable_i;
  logic [11:0] tb_paddr_i;
  logic  tb_pwrite_i;
  logic [31:0] tb_pwdata_i;
  logic  tb_adc_valid_i;
  logic [AdcW-1:0] tb_adc_data_i;
  logic [3:0] tb_ana_flag_i;

  cdriscv_32s_20_ams_if u_dut (
      .clk_i (clk),
      .rst_ni (rst_n),
      .psel_i (tb_psel_i),
      .penable_i (tb_penable_i),
      .paddr_i (tb_paddr_i),
      .pwrite_i (tb_pwrite_i),
      .pwdata_i (tb_pwdata_i),
      .prdata_o (),
      .pready_o (),
      .pslverr_o (),
      .adc_start_o (),
      .adc_ch_o (),
      .adc_valid_i (tb_adc_valid_i),
      .adc_data_i (tb_adc_data_i),
      .dac_data_o (),
      .dac_we_o (),
      .atest_en_o (),
      .atest_sel_o (),
      .ana_flag_i (tb_ana_flag_i),
      .irq_o (),
      .fault_o ()
  );

  int errors = 0, checks = 0;
  logic [1:0] idle, got, mask;
  int e, b;

  task automatic do_reset;
    rst_n = 0;
    tb_psel_i = '0;
    tb_penable_i = '0;
    tb_paddr_i = '0;
    tb_pwrite_i = '0;
    tb_pwdata_i = '0;
    tb_adc_valid_i = '1;
    tb_adc_data_i = '0;
    tb_ana_flag_i = '0;
    repeat (4) @(posedge clk);
    rst_n = 1;
    repeat (4) @(posedge clk);
  endtask

  initial begin
    do_reset();
    idle = u_dut.state_q;
    // Compare only the bits a flip-flop actually drives.  yosys
    // declares the state wire at its RTL width and optimises constant
    // bits away, so a four-bit declaration can have three flops and one
    // permanently floating bit -- and comparing that bit makes every
    // encoding look like a failure.
    mask = '0;
    for (b = 0; b < 2; b++)
      if (idle[b] === 1'b0 || idle[b] === 1'b1) mask[b] = 1'b1;
    $display("[fsm-cdriscv_32s_20_ams_if] idle=%b driven=%b", idle, mask);

    for (e = 0; e < 4; e++) begin
      do_reset();
      force u_dut.state_q = 2'(e);
      @(posedge clk);
      #1ns;
      release u_dut.state_q;
      repeat (8) @(posedge clk);
      checks++;
      got = u_dut.state_q;
      if (((got ^ idle) & mask) !== '0) begin
        $display("[fsm-cdriscv_32s_20_ams_if] FAIL: encoding %0d settled at %b, idle is %b",
                 e, got, idle);
        errors++;
      end
    end

    if (errors == 0)
      $display("[fsm-cdriscv_32s_20_ams_if] PASS: 4 encodings all recover to idle");
    else
      $display("[fsm-cdriscv_32s_20_ams_if] FAIL: %0d of %0d", errors, checks);
    $finish;
  end

  initial begin #5ms; $display("[fsm-cdriscv_32s_20_ams_if] FAIL: timeout"); $finish; end

endmodule
