// SPDX-FileCopyrightText: 2026 ChipDesign B.V.
// SPDX-License-Identifier: Apache-2.0
//
// cdriscv-32s-20 -- QSPI-master boot loader.
//
// On real silicon the I-TCM is volatile and empty at power-up; this
// block is the only path that fills it.  Out of reset it reads a boot
// image from an external SPI NOR flash, writes it into the TCMs over
// the normal data bus (through the subsystem's mux -- see
// cdriscv_32s_20_subsys), verifies a CRC32 over everything it wrote,
// and only then raises boot_done_o, which is what releases the core's
// fetch.  On any failure it retries the whole load from scratch up to
// RetryMax times and then latches boot_fault_o, sticky, with the core
// never released.
//
// ------------------------------------------------------------------
// Flash image format (all fields little-endian 32-bit words, image at
// flash offset 0; also documented in doc/programming_manual.md and
// generated by scripts/mkbootimg.py):
//
//   offset  word  field
//   0x00    0     MAGIC      32'hCD20_B007
//   0x04    1     FLAGS      bit 0: read the payload with the quad
//                            command (EBh); bits 31:1 reserved, MUST
//                            be zero (a set reserved bit is a boot
//                            fault, so a future format revision cannot
//                            be half-understood by this loader)
//   0x08    2     SEG0_DEST  byte address, word aligned (I-TCM segment)
//   0x0c    3     SEG0_LEN   bytes, word multiple, > 0
//   0x10    4     SEG1_DEST  byte address, word aligned (D-TCM segment)
//   0x14    5     SEG1_LEN   bytes, word multiple; 0 = segment absent
//                            (SEG1_DEST is then ignored)
//   0x18    6     CRC32      IEEE 802.3 CRC-32 (init 0xffffffff, poly
//                            0xedb88320 reflected, final xor
//                            0xffffffff -- the value python's
//                            binascii.crc32 returns) over the payload
//                            BYTES of both segments in read order:
//                            seg0 first, then seg1.  The header is not
//                            covered -- a corrupt header fails the
//                            magic / reserved-flag / bounds checks
//                            instead.
//   0x1c    7...  PAYLOAD    seg0 bytes immediately followed by seg1
//                            bytes, no padding between them
//
// Each segment must lie ENTIRELY inside the I-TCM or entirely inside
// the D-TCM address range (the Itcm*/Dtcm* parameters carry the same
// values the bus decode uses).  A segment that does not is a boot
// fault, and it is detected from the header BEFORE any bus write is
// issued -- a wild segment never writes anything.
//
// ------------------------------------------------------------------
// SPI protocol.  sclk = clk / SclkDiv (2 or 4), SPI mode 0: outputs
// change while sclk is low, both sides sample on the rising edge.
//
//   * Header: always command 03h (Read Data), 1-bit: opcode + 24-bit
//     address on IO0, data back on IO1.  During every 1-bit phase the
//     loader drives IO2/IO3 high -- on a real flash those pads are
//     WP#/HOLD# and floating them low would pause the device.
//   * Payload: command 03h again, or EBh (Quad I/O Fast Read) if
//     FLAGS[0] is set: opcode on IO0, then the 24-bit address plus the
//     mode byte 8'h00 on all four lines (mode 00 = do not arm the
//     "continuous read" mode), then QuadDummy dummy sclk cycles with
//     the loader's drivers released, then data nibbles on IO[3:0].
//     This matches the common NOR families (Winbond W25Qxx, Macronix
//     MX25Lxx, ISSI IS25LPxx) with QuadDummy=4; see
//     verif/models/spi_norflash_model.sv.
//
// The loader is the sclk master, so a flash cannot stall it; what CAN
// stop progress is the TCM side (the memory BIST owns the arrays while
// it runs -- hold_i pauses the loader without penalty) or an upset in
// this block itself.  A progress watchdog therefore bounds every byte
// and every bus beat to TimeoutCycles clk cycles; exceeding it is a
// failed attempt like a CRC mismatch.
//
// Retry policy: EVERY failure class -- bad magic, reserved flag,
// bounds, CRC, timeout, bus error response -- abandons the attempt
// (CS# raised at once) and restarts from scratch, because a header
// check can also fail from a transient read corruption that a re-read
// would clear.  After RetryMax retries (RetryMax+1 attempts in total)
// boot_fault_o latches sticky and the FSM parks: the core is NEVER
// released on a failed boot.
//
// Reset: the subsystem clocks this block on clk_i and resets it with
// the COLD reset only (rst_n_sync, not core_rst_n), so a warm reset --
// watchdog or safety-controller reset request -- restarts the core
// from the already-loaded, already-verified TCM image without a
// reload, exactly as the preloaded-TCM benches restart today.
// boot_done_o / boot_fault_o are sticky until the next cold reset.
//
// STATUS: block-verified (doc/variant_status.md, section 2) and
// instantiated by the subsystem.  No signoff gate is met in this
// repository -- see README.md.  NOT qualified for safety-critical use.

`default_nettype none

module cdriscv_32s_20_qspi_boot #(
    parameter int unsigned SclkDiv       = 2,     // sclk = clk/2 or clk/4
    parameter int unsigned RetryMax      = 3,     // retries after the first attempt
    parameter int unsigned TimeoutCycles = 1024,  // clk cycles per byte / bus beat
    parameter int unsigned QuadDummy     = 4,     // EBh dummy sclk cycles after the mode byte
    parameter logic [31:0] ItcmBase      = 32'h0000_0000,
    parameter int unsigned ItcmBytes     = 16384,
    parameter logic [31:0] DtcmBase      = 32'h1000_0000,
    parameter int unsigned DtcmBytes     = 16384
)(
    input  logic        clk_i,
    input  logic        rst_ni,

    // pause (the memory BIST owns the TCM arrays while it runs)
    input  logic        hold_i,

    // bus master, OBI-like, write-only (through the subsystem mux)
    output logic        mst_req_o,
    input  logic        mst_gnt_i,
    input  logic        mst_rvalid_i,
    output logic        mst_we_o,
    output logic [3:0]  mst_be_o,
    output logic [31:0] mst_addr_o,
    output logic [31:0] mst_wdata_o,
    input  logic        mst_err_i,

    // QSPI pads
    // Field telemetry: how many retries the successful (or final) boot
    // attempt consumed.  A unit that boots after two retries has a
    // degrading flash; without this register that fact is invisible
    // until it becomes a unit that does not boot at all.
    output logic [3:0]  boot_retries_o,

    output logic        qspi_sclk_o,
    output logic        qspi_cs_no,
    input  logic [3:0]  qspi_io_i,
    output logic [3:0]  qspi_io_o,
    output logic [3:0]  qspi_io_oe_o,

    // status (both sticky until the next cold reset)
    output logic        boot_done_o,
    output logic        boot_fault_o
);

  localparam logic [31:0] BootMagic  = 32'hCD20_B007;
  localparam logic [7:0]  CmdRead1   = 8'h03;   // Read Data, 1-bit
  localparam logic [7:0]  CmdReadQ   = 8'hEB;   // Quad I/O Fast Read
  localparam logic [23:0] PayloadOff = 24'd28;  // header is 7 words
  localparam int unsigned HalfDiv    = SclkDiv / 2;  // clk cycles per sclk half period

`ifndef SYNTHESIS
  initial begin
    if (SclkDiv != 2 && SclkDiv != 4)
      $fatal(1, "SclkDiv must be 2 or 4, not %0d", SclkDiv);
    if (RetryMax > 14)
      $fatal(1, "RetryMax must fit the 4-bit retry counter");
    if (QuadDummy < 1 || QuadDummy > 63)
      $fatal(1, "QuadDummy must be 1..63");
  end
`endif

  // ------------------------------------------------------------------
  // CRC-32 (IEEE 802.3), one byte per call, reflected form
  // ------------------------------------------------------------------
  function automatic logic [31:0] crc32_byte(input logic [31:0] c,
                                             input logic [7:0]  b);
    logic [31:0] r;
    r = c ^ {24'h0, b};
    for (int i = 0; i < 8; i++) begin
      r = (r >> 1) ^ (r[0] ? 32'hEDB8_8320 : 32'h0);
    end
    return r;
  endfunction

  // ------------------------------------------------------------------
  // Segment bounds: entirely inside ONE TCM, word aligned.  The 33-bit
  // end address keeps dest+len from wrapping past 2^32 unnoticed.
  // ------------------------------------------------------------------
  function automatic logic seg_in(input logic [31:0] dest,
                                  input logic [31:0] len,
                                  input logic [31:0] base,
                                  input logic [31:0] bytes);
    logic [32:0] seg_end, win_end;
    seg_end = {1'b0, dest} + {1'b0, len};
    win_end = {1'b0, base} + {1'b0, bytes};
    return (dest >= base) && (seg_end <= win_end);
  endfunction

  function automatic logic seg_ok(input logic [31:0] dest,
                                  input logic [31:0] len);
    return (dest[1:0] == 2'b00) && (len[1:0] == 2'b00) &&
           (seg_in(dest, len, ItcmBase, 32'(ItcmBytes)) ||
            seg_in(dest, len, DtcmBase, 32'(DtcmBytes)));
  endfunction

  // ------------------------------------------------------------------
  // State
  // ------------------------------------------------------------------
  typedef enum logic [2:0] {
    S_IDLE, S_HDR, S_CHECK, S_PAY, S_CRC, S_FAULT, S_DONE
  } state_e;

  typedef enum logic [2:0] {
    P_NONE, P_TX1, P_TX4, P_DUMMY, P_D1, P_D4, P_GAP
  } phase_e;

  state_e      state_q;
  phase_e      phase_q;

  logic        sclk_q, cs_n_q;
  logic [1:0]  div_q;
  logic [5:0]  bitcnt_q;       // sclk rises inside the current phase
  logic [5:0]  tx1len_q;       // P_TX1 length in bits (8 or 32)
  logic [31:0] tx_q;           // MSB-first shift-out (bits or nibbles)
  logic [6:0]  rx_q;           // shift-in assembly (byte completes with the live bits)
  logic [23:0] bytes_left_q;   // bytes still to receive in this command
  logic [3:0]  gap_q;          // CS# high recovery counter

  logic [223:0] hdr_q;         // 28 header bytes, first byte ends at [7:0]

  logic [31:0] crc_q;
  logic [23:0] word_q;         // payload word assembly (LE, low three bytes)
  logic [1:0]  wbcnt_q;        // bytes collected into word_q
  logic        use_quad_q;

  logic [31:0] cur_addr_q;     // next TCM write address
  logic [23:0] seg_left_q;     // bytes left in the current segment
  logic        in_seg1_q;

  logic        wr_pending_q, wr_gntd_q;
  logic [31:0] wr_addr_q, wr_data_q;

  logic [3:0]  retries_q;
  logic [31:0] wdog_q;

  logic        boot_done_q, boot_fault_q;

  // ---- header fields, as wires over the byte shift register --------
  logic [31:0] hdr_magic_w, hdr_flags_w, hdr_d0_w, hdr_l0_w;
  logic [31:0] hdr_d1_w, hdr_l1_w, hdr_crc_w;
  assign hdr_magic_w = hdr_q[31:0];
  assign hdr_flags_w = hdr_q[63:32];
  assign hdr_d0_w    = hdr_q[95:64];
  assign hdr_l0_w    = hdr_q[127:96];
  assign hdr_d1_w    = hdr_q[159:128];
  assign hdr_l1_w    = hdr_q[191:160];
  assign hdr_crc_w   = hdr_q[223:192];

  // ---- header validation (combinational, used in S_CHECK) ----------
  logic hdr_magic_ok_w, hdr_flags_ok_w, seg_bounds_ok_w, hdr_ok_w;
  logic seg0_ok_w, seg1_ok_w, use_quad_w;

  assign hdr_magic_ok_w = (hdr_magic_w == BootMagic);
  assign hdr_flags_ok_w = (hdr_flags_w[31:1] == 31'b0);
  assign seg0_ok_w      = (hdr_l0_w != 32'd0) && seg_ok(hdr_d0_w, hdr_l0_w);
  assign seg1_ok_w      = (hdr_l1_w == 32'd0) || seg_ok(hdr_d1_w, hdr_l1_w);
  assign seg_bounds_ok_w = seg0_ok_w && seg1_ok_w;
  assign hdr_ok_w       = hdr_magic_ok_w && hdr_flags_ok_w && seg_bounds_ok_w;
  assign use_quad_w     = hdr_flags_w[0];

  logic [31:0] crc_calc_w;
  assign crc_calc_w = crc_q ^ 32'hFFFF_FFFF;

  // ------------------------------------------------------------------
  // SPI engine strobes
  // ------------------------------------------------------------------
  logic spi_shifting, spi_run, spi_edge, spi_rise, spi_fall;

  assign spi_shifting = (phase_q == P_TX1) || (phase_q == P_TX4) ||
                        (phase_q == P_DUMMY) || (phase_q == P_D1) ||
                        (phase_q == P_D4);
  assign spi_run  = spi_shifting && !wr_pending_q && !hold_i;
  assign spi_edge = spi_run && (div_q == 2'(HalfDiv - 1));
  assign spi_rise = spi_edge && !sclk_q;
  assign spi_fall = spi_edge &&  sclk_q;

  // last sclk rise of the current phase
  logic [5:0] phase_bits_w;
  always_comb begin
    unique case (phase_q)
      P_TX1:   phase_bits_w = tx1len_q;
      P_TX4:   phase_bits_w = 6'd8;               // 6 addr + 2 mode nibbles
      P_DUMMY: phase_bits_w = 6'(QuadDummy);
      P_D1:    phase_bits_w = 6'd8;               // per byte
      P_D4:    phase_bits_w = 6'd2;               // per byte
      default: phase_bits_w = 6'd1;
    endcase
  end

  logic last_rise_w;                              // this rise ends the phase/byte
  assign last_rise_w = (bitcnt_q == phase_bits_w - 6'd1);

  // received byte, complete on the last rise of a data byte
  logic       byte_done_w;
  logic [7:0] rx_byte_w;
  assign byte_done_w = spi_rise && last_rise_w &&
                       ((phase_q == P_D1) || (phase_q == P_D4));
  assign rx_byte_w   = (phase_q == P_D1) ? {rx_q[6:0], qspi_io_i[1]}
                                         : {rx_q[3:0], qspi_io_i};

  // ------------------------------------------------------------------
  // Failure detection -- every failure class in one wire, so the retry
  // policy exists exactly once (the fail handler at the bottom of the
  // sequential process, which runs LAST and therefore wins over the
  // engine's same-cycle assignments)
  // ------------------------------------------------------------------
  logic timeout_w;
  assign timeout_w = (wdog_q >= 32'(TimeoutCycles));

  logic fail_w;
  assign fail_w =
      (((state_q == S_HDR) || (state_q == S_PAY)) && timeout_w) ||
      ((state_q == S_CHECK) && !hdr_ok_w) ||
      ((state_q == S_CRC) && (crc_calc_w != hdr_crc_w)) ||
      (wr_pending_q && mst_rvalid_i && mst_err_i);

  always_ff @(posedge clk_i or negedge rst_ni) begin
    if (!rst_ni) begin
      state_q      <= S_IDLE;
      phase_q      <= P_NONE;
      sclk_q       <= 1'b0;
      cs_n_q       <= 1'b1;
      div_q        <= 2'b0;
      bitcnt_q     <= 6'b0;
      tx1len_q     <= 6'b0;
      tx_q         <= 32'b0;
      rx_q         <= 7'b0;
      bytes_left_q <= 24'b0;
      gap_q        <= 4'b0;
      hdr_q        <= 224'b0;
      crc_q        <= 32'b0;
      word_q       <= 24'b0;
      wbcnt_q      <= 2'b0;
      use_quad_q   <= 1'b0;
      cur_addr_q   <= 32'b0;
      seg_left_q   <= 24'b0;
      in_seg1_q    <= 1'b0;
      wr_pending_q <= 1'b0;
      wr_gntd_q    <= 1'b0;
      wr_addr_q    <= 32'b0;
      wr_data_q    <= 32'b0;
      retries_q    <= 4'b0;
      wdog_q       <= 32'b0;
      boot_done_q  <= 1'b0;
      boot_fault_q <= 1'b0;
    end else begin

      // ---- progress watchdog --------------------------------------
      // Cleared by every completed byte and every completed bus beat;
      // paused (held clear) while the BIST holds us or nothing is in
      // flight.  Anything else that stops progress -- a bus that never
      // grants, an upset phase register -- trips it.
      if ((state_q == S_IDLE) || (state_q == S_DONE) || (state_q == S_FAULT) ||
          hold_i || byte_done_w || mst_rvalid_i) begin
        wdog_q <= 32'b0;
      end else begin
        wdog_q <= wdog_q + 32'd1;
      end

      // ---- SPI clock divider / edges ------------------------------
      if (!spi_run) begin
        div_q <= 2'b0;
      end else if (spi_edge) begin
        div_q  <= 2'b0;
        sclk_q <= ~sclk_q;
      end else begin
        div_q <= div_q + 2'd1;
      end

      // ---- rise: sample and count ---------------------------------
      if (spi_rise) begin
        if (phase_q == P_D1) rx_q      <= {rx_q[5:0], qspi_io_i[1]};
        if (phase_q == P_D4) rx_q[3:0] <= qspi_io_i;
        if (last_rise_w) bitcnt_q <= 6'b0;
        else             bitcnt_q <= bitcnt_q + 6'd1;
        if (byte_done_w) begin
          bytes_left_q <= bytes_left_q - 24'd1;
        end
      end

      // ---- fall: shift out / advance phases -----------------------
      if (spi_fall) begin
        if (bitcnt_q == 6'b0) begin
          // the fall after a phase's (or byte's) last rise
          unique case (phase_q)
            P_TX1: begin
              if (use_quad_q && (state_q == S_PAY)) begin
                tx_q    <= {PayloadOff, 8'h00};   // address + mode byte
                phase_q <= P_TX4;
              end else begin
                phase_q <= P_D1;
              end
            end
            P_TX4:   phase_q <= P_DUMMY;
            P_DUMMY: phase_q <= P_D4;
            P_D1, P_D4: begin
              if (bytes_left_q == 24'b0) begin
                cs_n_q  <= 1'b1;
                phase_q <= P_GAP;
                gap_q   <= 4'h7;
              end
            end
            default: ;
          endcase
        end else begin
          if (phase_q == P_TX1) tx_q <= {tx_q[30:0], 1'b0};
          if (phase_q == P_TX4) tx_q <= {tx_q[27:0], 4'b0};
        end
      end

      // ---- received bytes -----------------------------------------
      if (byte_done_w && (state_q == S_HDR)) begin
        hdr_q  <= {rx_byte_w, hdr_q[223:8]};
      end
      if (byte_done_w && (state_q == S_PAY)) begin
        crc_q  <= crc32_byte(crc_q, rx_byte_w);
        word_q <= {rx_byte_w, word_q[23:8]};
        wbcnt_q <= wbcnt_q + 2'd1;
        if (wbcnt_q == 2'd3) begin
          wr_pending_q <= 1'b1;
          wr_gntd_q    <= 1'b0;
          wr_addr_q    <= cur_addr_q;
          wr_data_q    <= {rx_byte_w, word_q};
        end
      end

      // ---- bus write handshake (an err response raises fail_w) ----
      if (wr_pending_q) begin
        if (!wr_gntd_q && mst_gnt_i) wr_gntd_q <= 1'b1;
        if (mst_rvalid_i) begin
          wr_pending_q <= 1'b0;
          wr_gntd_q    <= 1'b0;
          cur_addr_q   <= cur_addr_q + 32'd4;
          if (seg_left_q == 24'd4 && !in_seg1_q && (hdr_l1_w != 32'd0)) begin
            cur_addr_q <= hdr_d1_w;
            seg_left_q <= hdr_l1_w[23:0];
            in_seg1_q  <= 1'b1;
          end else begin
            seg_left_q <= seg_left_q - 24'd4;
          end
        end
      end

      // ---- top-level FSM ------------------------------------------
      if (!fail_w) begin
      unique case (state_q)
        S_IDLE: begin
          if (gap_q != 4'b0) begin
            gap_q <= gap_q - 4'd1;
          end else if (!hold_i) begin
            // start (or restart) an attempt: read the 28-byte header
            crc_q        <= 32'hFFFF_FFFF;
            wbcnt_q      <= 2'b0;
            in_seg1_q    <= 1'b0;
            use_quad_q   <= 1'b0;
            cs_n_q       <= 1'b0;
            sclk_q       <= 1'b0;
            div_q        <= 2'b0;
            bitcnt_q     <= 6'b0;
            tx_q         <= {CmdRead1, 24'h0};
            tx1len_q     <= 6'd32;
            bytes_left_q <= 24'd28;
            phase_q      <= P_TX1;
            state_q      <= S_HDR;
          end
        end

        S_HDR: begin
          if (phase_q == P_GAP) begin
            if (gap_q != 4'b0) gap_q <= gap_q - 4'd1;
            else begin
              phase_q <= P_NONE;
              state_q <= S_CHECK;
            end
          end
        end

        S_CHECK: begin
          // a wild segment (or bad magic / reserved flag) raised fail_w
          // combinationally, BEFORE any bus write exists to refuse --
          // this arm only runs on a valid header
          begin
            use_quad_q   <= use_quad_w;
            cur_addr_q   <= hdr_d0_w;
            seg_left_q   <= hdr_l0_w[23:0];
            bytes_left_q <= hdr_l0_w[23:0] + hdr_l1_w[23:0];
            cs_n_q       <= 1'b0;
            sclk_q       <= 1'b0;
            div_q        <= 2'b0;
            bitcnt_q     <= 6'b0;
            if (use_quad_w) begin
              tx_q     <= {CmdReadQ, 24'h0};
              tx1len_q <= 6'd8;
            end else begin
              tx_q     <= {CmdRead1, PayloadOff};
              tx1len_q <= 6'd32;
            end
            phase_q <= P_TX1;
            state_q <= S_PAY;
          end
        end

        S_PAY: begin
          if (phase_q == P_GAP) begin
            if (gap_q != 4'b0) gap_q <= gap_q - 4'd1;
            else begin
              phase_q <= P_NONE;
              state_q <= S_CRC;
            end
          end
        end

        S_CRC: begin
          // a CRC mismatch raised fail_w; only a verified image gets here
          boot_done_q <= 1'b1;
          state_q     <= S_DONE;
        end

        // S_FAULT parks forever; boot_fault_q stays latched
        S_FAULT: state_q <= S_FAULT;
        S_DONE:  state_q <= S_DONE;

        default: state_q <= S_IDLE;   // upset recovery
      endcase
      end else begin
        // ---- the one failure handler (fail_w): raise CS#, kill the
        // engine, count the attempt -- runs last, so it wins over any
        // same-cycle engine assignment above
        cs_n_q       <= 1'b1;
        sclk_q       <= 1'b0;
        phase_q      <= P_NONE;
        wr_pending_q <= 1'b0;
        wr_gntd_q    <= 1'b0;
        gap_q        <= 4'hf;
        if (retries_q >= 4'(RetryMax)) begin
          boot_fault_q <= 1'b1;
          state_q      <= S_FAULT;
        end else begin
          retries_q <= retries_q + 4'd1;
          state_q   <= S_IDLE;
        end
      end
    end
  end

  // ------------------------------------------------------------------
  // Outputs
  // ------------------------------------------------------------------
  assign mst_req_o   = wr_pending_q && !wr_gntd_q;
  assign mst_we_o    = 1'b1;
  assign mst_be_o    = 4'b1111;
  assign mst_addr_o  = wr_addr_q;
  assign mst_wdata_o = wr_data_q;

  assign qspi_sclk_o = sclk_q;
  assign qspi_cs_no  = cs_n_q;

  always_comb begin
    qspi_io_o    = 4'b0000;
    qspi_io_oe_o = 4'b0000;
    unique case (phase_q)
      P_TX1: begin
        qspi_io_o    = {2'b11, 1'b0, tx_q[31]};  // HOLD#/WP# high, IO0 = bit
        qspi_io_oe_o = 4'b1101;
      end
      P_TX4: begin
        qspi_io_o    = tx_q[31:28];
        qspi_io_oe_o = 4'b1111;
      end
      P_D1: begin
        qspi_io_o    = 4'b1100;                  // HOLD#/WP# high, IO0 parked low
        qspi_io_oe_o = 4'b1101;
      end
      default: ;                                 // P_DUMMY / P_D4 / idle: released
    endcase
  end

  assign boot_done_o  = boot_done_q;
  assign boot_retries_o = retries_q;
  assign boot_fault_o = boot_fault_q;

endmodule

`default_nettype wire
