#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 ChipDesign B.V.
# SPDX-License-Identifier: Apache-2.0
#
# Random RV32IM program generator for the Spike co-simulation.
#
#   python3 verif/core/gen_random_prog.py <out.S> --seed N --count M
#
# The generator is deliberately constrained rather than uniformly
# random, so that every program terminates and every difference between
# Spike and the RTL is a real difference:
#
#   * memory accesses are forced into a scratch area with a masked
#     offset, so nothing escapes the TCM and no access faults appear
#     unless a test asks for them
#   * branches only ever jump forward by a small amount, so control
#     flow is a DAG and the program cannot loop for ever
#   * no jalr with a computed target, no counter CSRs (mcycle and
#     minstret legitimately differ between model and RTL), no fence.i
#   * x0 is used as a destination sometimes, on purpose
#   * the register pool excludes sp and the base register, which are set
#     up once at the start and never clobbered
#
# What it does exercise: every ALU form, the whole M extension, all load
# and store widths and alignments, and branches in both directions with
# operands that were themselves randomly produced.

import argparse
import random

# x5..x31 minus x8 (base pointer), x31 (outer loop counter) and x2 (sp)
POOL = [r for r in range(5, 31) if r not in (8,)]
BASE = 8
LOOPCNT = 31

RR = ["add", "sub", "sll", "slt", "sltu", "xor", "srl", "sra", "or", "and",
      "mul", "mulh", "mulhsu", "mulhu", "div", "divu", "rem", "remu"]
RI = ["addi", "slti", "sltiu", "xori", "ori", "andi"]
SH = ["slli", "srli", "srai"]
LD = [("lw", 4), ("lh", 2), ("lhu", 2), ("lb", 1), ("lbu", 1)]
ST = [("sw", 4), ("sh", 2), ("sb", 1)]
BR = ["beq", "bne", "blt", "bge", "bltu", "bgeu"]

SCRATCH_WORDS = 32


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("out")
    ap.add_argument("--seed", type=int, default=1)
    ap.add_argument("--count", type=int, default=400)
    ap.add_argument("--loops", type=int, default=1,
                    help="wrap the body in a bounded outer loop, so that a "
                         "small image executes many instructions.  The body "
                         "is not repeated work: the registers carry over, so "
                         "each iteration starts from a different state.")
    args = ap.parse_args()

    rng = random.Random(args.seed)
    body = []
    label = 0

    # pending forward branch targets: label -> instructions still to emit
    pending = []

    for n in range(args.count):
        # land any forward branch whose target we have reached
        for lab in [l for (l, at) in pending if at <= n]:
            body.append("L%d:" % lab)
        pending = [(l, at) for (l, at) in pending if at > n]

        kind = rng.choices(
            ["rr", "ri", "sh", "ld", "st", "br", "lui", "auipc"],
            weights=[34, 18, 10, 12, 10, 10, 3, 3])[0]

        rd = rng.choice(POOL + [0])
        rs1 = rng.choice(POOL)
        rs2 = rng.choice(POOL)

        if kind == "rr":
            body.append("    %-7s x%d, x%d, x%d" % (rng.choice(RR), rd, rs1, rs2))
        elif kind == "ri":
            body.append("    %-7s x%d, x%d, %d"
                        % (rng.choice(RI), rd, rs1, rng.randint(-2048, 2047)))
        elif kind == "sh":
            body.append("    %-7s x%d, x%d, %d"
                        % (rng.choice(SH), rd, rs1, rng.randint(0, 31)))
        elif kind == "lui":
            body.append("    %-7s x%d, %d" % ("lui", rd, rng.randint(0, 0xfffff)))
        elif kind == "auipc":
            body.append("    %-7s x%d, %d" % ("auipc", rd, rng.randint(0, 0xff)))
        elif kind in ("ld", "st"):
            op, width = rng.choice(LD if kind == "ld" else ST)
            # aligned offsets inside the scratch area; the misaligned
            # cases are directed tests, not random ones, because they
            # trap and would end the program
            off = rng.randrange(0, SCRATCH_WORDS * 4, width)
            if kind == "ld":
                body.append("    %-7s x%d, %d(x%d)" % (op, rd, off, BASE))
            else:
                body.append("    %-7s x%d, %d(x%d)" % (op, rs2, off, BASE))
        elif kind == "br":
            ahead = rng.randint(1, 4)
            body.append("    %-7s x%d, x%d, L%d" % (rng.choice(BR), rs1, rs2, label))
            pending.append((label, n + ahead))
            label += 1

    # land anything still pending
    for lab, _ in pending:
        body.append("L%d:" % lab)

    with open(args.out, "w") as f:
        f.write("/* SPDX-License-Identifier: Apache-2.0\n"
                " * Generated by verif/core/gen_random_prog.py, seed %d, %d instructions.\n"
                " * Do not edit: regenerate instead.\n */\n\n"
                % (args.seed, args.count))
        f.write("    .section .text.init, \"ax\"\n    .global _start\n_start:\n")
        # deterministic start state on both sides
        for r in range(1, 32):
            f.write("    li      x%d, 0\n" % r)
        f.write("    la      sp, _stack_top\n")
        f.write("    la      x%d, scratch\n" % BASE)
        # seed the pool with varied values, including the boundaries
        seeds = [0, 1, -1, 0x7fffffff, -2147483648, 0x55555555, -1431655766]
        for i, r in enumerate(POOL):
            f.write("    li      x%d, %d\n" % (r, seeds[i % len(seeds)] if i < 14
                                               else rng.randint(-2**31, 2**31 - 1)))
        f.write("\n")
        if args.loops > 1:
            f.write("    li      x%d, %d\n" % (LOOPCNT, args.loops))
            f.write("outer:\n")
        f.write("\n".join(body))
        if args.loops > 1:
            f.write("\n    addi    x%d, x%d, -1\n" % (LOOPCNT, LOOPCNT))
            f.write("    bne     x%d, x0, outer\n" % LOOPCNT)
        f.write("\n\ndone:\n"
                "    la      x5, tohost\n"
                "    li      x6, 1\n"
                "    sw      x6, 0(x5)\n"
                "1:  j       1b\n\n"
                "fail:\n"
                "    la      x5, tohost\n"
                "    li      x6, 3\n"
                "    sw      x6, 0(x5)\n"
                "2:  j       2b\n\n")
        f.write("    .section .tohost, \"aw\", @progbits\n    .align 3\n"
                "    .global tohost\ntohost:\n    .dword 0\n"
                "    .global fromhost\nfromhost:\n    .dword 0\n\n")
        f.write("    .section .data\n    .align 4\nscratch:\n")
        for _ in range(SCRATCH_WORDS):
            f.write("    .word 0x%08x\n" % rng.getrandbits(32))


if __name__ == "__main__":
    main()
