#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 ChipDesign B.V.
# SPDX-License-Identifier: Apache-2.0
#
# Generates an illegal-state-recovery bench for one module.
#
# Coverage waiver W2a keeps the `default:` arms of six state machines
# because they return the machine to a defined state after an upset, and
# says that argument has to be re-made against the netlist. Doing that
# by hand costs a testbench per module, most of it port wiring, so the
# port list is read from the RTL instead.
#
# Inputs are tied off and outputs left open: the machine is held
# quiescent, forced into every encoding its state register allows, and
# required to come back to the state it holds after reset. What is being
# tested is the recovery, not the function.
#
# Some inputs have to be tied *high* rather than low, and which ones is
# not a detail. A machine whose handshake inputs are all zero will sit
# for ever in a legal state waiting for a response, and the bench then
# reports a recovery failure that is nothing of the kind -- the LSU does
# exactly this if `data_gnt_i` and `data_rvalid_i` are left low. The
# fifth argument names the inputs to hold high so that any transaction
# the forced state implies can complete.
#
# The bench must run against a *standalone* netlist. In the flattened
# subsystem the state register is re-encoded by yosys's FSM passes and
# survives only as an escaped identifier with optimised-away bits; see
# finding V24.

import re
import sys

PARAM = re.compile(
    r"^\s*parameter\s+(?:int\s+unsigned\s+|int\s+|logic\s*\[[^\]]*\]\s*|bit\s+)?"
    r"(\w+)\s*=\s*([^,\n)]+)", re.M)

PORT = re.compile(
    r"^\s*(input|output)\s+(?:wire\s+|logic\s+|reg\s+)?"
    r"(?:(\[[^\]]+\])\s+)?(\w+)\s*[,)]", re.M)


def params(path, module):
    # Port widths can depend on the module's parameters, so the bench
    # needs them as localparams or it will not elaborate.
    text = open(path, errors="replace").read()
    i = text.index("module " + module)
    j = text.index(")(", i) if ")(" in text[i:i + 4000] else i
    return PARAM.findall(text[i:j]) if j > i else []


def ports(path, module):
    text = open(path, errors="replace").read()
    i = text.index("module " + module)
    j = text.index(");", i)
    out = []
    for d, width, name in PORT.findall(text[i:j] + ")"):
        out.append((d, width or "", name))
    return out


def main():
    rtl, module, state, width, out = sys.argv[1:6]
    high = set(sys.argv[6].split(",")) if len(sys.argv) > 6 and sys.argv[6] else set()
    w = int(width)
    pl = ports(rtl, module)
    pr = params(rtl, module)
    decls, conns = [], []
    for d, wd, name in pl:
        if name in ("clk_i", "rst_ni"):
            conns.append("      .%s (%s)" % (name, "clk" if name == "clk_i" else "rst_n"))
            continue
        if d == "input":
            decls.append("  logic %s %s;" % (wd, "tb_" + name))
            conns.append("      .%s (tb_%s)" % (name, name))
        else:
            conns.append("      .%s ()" % name)
    ties = "\n".join("    tb_%s = %s;" % (n, "'1" if n in high else "'0")
                     for d, _, n in pl
                     if d == "input" and n not in ("clk_i", "rst_ni"))

    src = f"""// SPDX-FileCopyrightText: 2026 ChipDesign B.V.
// SPDX-License-Identifier: Apache-2.0
//
// GENERATED by scripts/gen_fsm_bench.py -- do not edit by hand.
//
// Illegal state recovery for {module}, on its gate netlist.
// See coverage waiver W2a and finding V24.

`default_nettype none
`timescale 1ns/1ps

module tb_fsm_{module};

  logic clk = 0, rst_n;
  always #5ns clk = ~clk;

{chr(10).join("  localparam int %s = %s;" % (n, v.strip()) for n, v in pr)}

{chr(10).join(decls)}

  {module} u_dut (
{(',' + chr(10)).join(conns)}
  );

  int errors = 0, checks = 0;
  logic [{w-1}:0] idle, got, mask;
  int e, b;

  task automatic do_reset;
    rst_n = 0;
{ties}
    repeat (4) @(posedge clk);
    rst_n = 1;
    repeat (4) @(posedge clk);
  endtask

  initial begin
    do_reset();
    idle = u_dut.{state};
    // Compare only the bits a flip-flop actually drives.  yosys
    // declares the state wire at its RTL width and optimises constant
    // bits away, so a four-bit declaration can have three flops and one
    // permanently floating bit -- and comparing that bit makes every
    // encoding look like a failure.
    mask = '0;
    for (b = 0; b < {w}; b++)
      if (idle[b] === 1'b0 || idle[b] === 1'b1) mask[b] = 1'b1;
    $display("[fsm-{module}] idle=%b driven=%b", idle, mask);

    for (e = 0; e < {2**w}; e++) begin
      do_reset();
      force u_dut.{state} = {w}'(e);
      @(posedge clk);
      #1ns;
      release u_dut.{state};
      repeat (8) @(posedge clk);
      checks++;
      got = u_dut.{state};
      if (((got ^ idle) & mask) !== '0) begin
        $display("[fsm-{module}] FAIL: encoding %0d settled at %b, idle is %b",
                 e, got, idle);
        errors++;
      end
    end

    if (errors == 0)
      $display("[fsm-{module}] PASS: {2**w} encodings all recover to idle");
    else
      $display("[fsm-{module}] FAIL: %0d of %0d", errors, checks);
    $finish;
  end

  initial begin #5ms; $display("[fsm-{module}] FAIL: timeout"); $finish; end

endmodule
"""
    open(out, "w").write(src)
    print("wrote %s (%d ports)" % (out, len(pl)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
